package ExceptionThrowTest;

public class ArithmeticExceptionThrowTest {
    public static void main(String[] args) {
        int a = 4/0;
        System.out.println(a);
    }
}
